#!/usr/bin/python3
"""test_base_models is dedicate to test base_model module
    and his has one unittst class and many function for testing
"""
import unittest
import json
from models.user import User
from datetime import datetime as dtime


class TestBaseModel(unittest.TestCase):
    """
        this is the class that was didicated for testing
        all BaseMode methods
    """
    def test_init(self):
        """test if the unite test qork is inteded for example
        check if updated_at != created_at
        """
        user = User()
        user.save()
        self.assertNotEqual(user.created_at, user.updated_at)
        self.assertEqual(user.email, "")
        self.assertEqual(user.password, "")
        self.assertEqual(user.first_name, "")
        self.assertEqual(user.last_name, "")

    def test_save(self):
        """this method for testing if the aboject that was create
            is stored in json file
        """
        user = User()
        user.email = "example@mail.com"
        user.password = "password"
        user.first_name = "firstName"
        user.last_name = "lastName"
        user.save()
        found = False
        found_data = {}
        with open("file.json", "r") as f:
            jdata = json.load(f)
        for key in jdata.keys():
            obj_id = key.split(".")[1]
            if obj_id == user.id:
                found = True
                found_data = jdata[key]
        self.assertTrue(found)
        self.assertEqual(found_data["email"], user.email)
        self.assertEqual(found_data["password"], user.password)
        self.assertEqual(found_data["first_name"], user.first_name)
        self.assertEqual(found_data["last_name"], user.last_name)

    def test_to_dict(self):
        """this functio test if the data that was generated by
        to_dict() method is the same data that was stored in json file"""
        user = User()
        user.save()
        found = {}
        with open("file.json", "r") as f:
            jdata = json.load(f)
        for key in jdata.keys():
            obj_id = key.split(".")[1]
            if obj_id == user.id:
                found = jdata[key]
        self.assertEqual(found, user.to_dict())


if __name__ == '__main__':
    unittest.main()
