#!/usr/bin/python3
"""test_base_models is dedicate to test base_model module
    and his has one unittst class and many function for testing
"""
import unittest
import json
from models.place import Place
from datetime import datetime as dtime


class TestBaseModel(unittest.TestCase):
    """
        this is the class that was didicated for testing
        all BaseMode methods
    """
    def test_init(self):
        """test if the unite test qork is inteded for example
        check if updated_at != created_at
        """
        place = Place()
        place.save()
        self.assertNotEqual(place.created_at, place.updated_at)

    def test_save(self):
        """this method for testing if the aboject that was create
            is stored in json file
        """
        place = Place()
        place.save()
        found = False
        with open("file.json", "r") as f:
            jdata = json.load(f)
        for key in jdata.keys():
            obj_id = key.split(".")[1]
            if obj_id == place.id:
                found = True
        self.assertTrue(found)

    def test_to_dict(self):
        """this functio test if the data that was generated by
        to_dict() method is the same data that was stored in json file"""
        place = Place()
        place.save()
        found = {}
        with open("file.json", "r") as f:
            jdata = json.load(f)
        for key in jdata.keys():
            obj_id = key.split(".")[1]
            if obj_id == place.id:
                found = jdata[key]
        self.assertEqual(found, place.to_dict())


if __name__ == '__main__':
    unittest.main()
