#!/usr/bin/python3
"""test_base_models is dedicate to test base_model module
    and his has one unittst class and many function for testing
"""
import unittest
import json
from models.review import Review
from datetime import datetime as dtime


class TestBaseModel(unittest.TestCase):
    """
        this is the class that was didicated for testing
        all BaseMode methods
    """
    def test_init(self):
        """test if the unite test qork is inteded for example
        check if updated_at != created_at
        """
        review = Review()
        review.save()
        self.assertNotEqual(review.created_at, review.updated_at)
        self.assertEqual(review.place_id, "")
        self.assertEqual(review.user_id, "")
        self.assertEqual(review.text, "")

    def test_save(self):
        """this method for testing if the aboject that was create
            is stored in json file
        """
        review = Review()
        review.place_id = "564894"
        review.user_id = "98784-478820-6t44"
        review.text = "hello world"

        review.save()
        found = False
        with open("file.json", "r") as f:
            jdata = json.load(f)
        found_data = {}
        for key in jdata.keys():
            obj_id = key.split(".")[1]
            if obj_id == review.id:
                found_data = jdata[key]
                found = True
        self.assertTrue(found)
        self.assertEqual(review.place_id, found_data['place_id'])
        self.assertEqual(review.user_id, found_data['user_id'])
        self.assertEqual(review.text, found_data['text'])

    def test_to_dict(self):
        """this functio test if the data that was generated by
        to_dict() method is the same data that was stored in json file"""
        review = Review()
        review.save()
        found = {}
        with open("file.json", "r") as f:
            jdata = json.load(f)
        for key in jdata.keys():
            obj_id = key.split(".")[1]
            if obj_id == review.id:
                found = jdata[key]
        self.assertEqual(found, review.to_dict())


if __name__ == '__main__':
    unittest.main()
